### ISSUE TITLE
Exception is not being caught if connection failes in Relay connect

### ISSUE THREAD

**Issue by vishalxl** [vishalxl/nostr_console#1]
Following is seen as of right now

```
... 498549ba698f7ccffb724071c3c2aa747ec3fb89cde5055404ba55327875de5645bd4645cb1b"}]
["EOSE","latest"]
Unhandled exception:
WebSocketException: Connection to 'https://nostr.rocks:0#' was not upgraded to websocket
#0      _WebSocketImpl.connect (dart:_http/websocket_impl.dart:1011:41)
#1      WebSocket.connect (dart:_http/websocket.dart:320:22)
#2      Relays.connect (package:nostr_console/relays.dart:36:25)
#3      getFeed (package:nostr_console/relays.dart:83:12)
#4      main.<anonymous closure> (file:///C:/Users/Vishal/source/dart/nostr_console/bin/nostr_console.dart:24:9)
#5      new Future.delayed.<anonymous closure> (dart:async/future.dart:424:39)
#6      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#7      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#8      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

**Comment by vishalxl** [comment]
Presently, as of aug 2022, this issue is not seen. 

The application does not crash or misbehave if no internet is there. Exceptions are caught and error(s) displayed.
