### ISSUE TITLE
Google translate is giving unhandled exception and crashing the application 

### ISSUE THREAD

**Issue by vishalxl** [vishalxl/nostr_console#12]
```
Unhandled exception:
Connection closed before full header was received
#0      IOClient.send (package:http/src/io_client.dart:90:7)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93:32)
<asynchronous suspension>
#2      _withClient (package:http/http.dart:164:12)
<asynchronous suspension>
#3      GoogleTranslator.translate (package:translator/src/google_translator.dart:51:18)
<asynchronous suspension>
```

**Comment by vishalxl** [comment]
Seeing this likely unrelated error 

```
Refreshing...
Unhandled exception:
Instance of 'LanguageNotSupportedException'
#0      LanguageList.[] (package:translator/src/langs/language.dart:128:5)
#1      GoogleTranslator.translate (package:translator/src/google_translator.dart:79:36)
<asynchronous suspension>
```

**Comment by vishalxl** [comment]
Fixed it by catching the exception.
