### ISSUE TITLE
Certificate verify failed when connecting to nostr-relay.freeberty.net

### ISSUE THREAD

**Issue by vishalxl** [vishalxl/nostr_console#2]
```
sending request ["REQ","latest",{ "authors": ["1f5cd0b7618dcd0b4040e0daa1e6719ae9e4b5c0822fc5f47ed55725e08b6564"], "limit": 20  } ] to wss://nostr.onsats.org
waiting for feed to come in
Error: Could not connect to wss://nostr-relay.freeberty.net
Unhandled exception:
HandshakeException: Handshake error in client (OS Error:
        CERTIFICATE_VERIFY_FAILED: self signed certificate(../../third_party/boringssl/src/ssl/handshake.cc:393))
#0      _SecureFilterImpl._handshake (dart:io-patch/secure_socket_patch.dart:99:46)
#1      _SecureFilterImpl.handshake (dart:io-patch/secure_socket_patch.dart:142:25)
#2      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:911:54)
#3      _RawSecureSocket._tryFilter (dart:io/secure_socket.dart:1040:19)
<asynchronous suspension>
```

**Comment by vishalxl** [comment]
When invoked as 
```
dart run bin/nostr_console.dart   --file=temp1.txt   --  --relay=wss://nostr-relay.freeberty.net
```

we don't see this error about certificate.

```
Going to use relay: wss://nostr-relay.freeberty.net
Going to use file to read from and store events: temp1.txt
Reading events from the given file.......read 11818 posts from file "temp1.txt"
Waiting for user posts to come in.....
Warning: In SendRequest creating connection onError. Kindly check your internet connection or change the relay by command line --relay=<relay wss url>

...received 0 posts made by the user
Waiting for feed to come in..............received 237 posts from the follows
Waiting for rest of posts to come in.....received 0 other posts


                                                       +-------+
                                                       |Author : 38b  id: 14d  Time: 04:58 AM Aug 20, 2022
                                                       |Message: Day #19: At times I feel slim other times I feel my gut anyway I MISS CANDY


```
