### ISSUE TITLE
Unhandled Exception / Handshake Exception : `Handshake error in client` HANDSHAKE_FAILURE_ON_CLIENT_HELLO

### ISSUE THREAD

**Issue by jnmclarty** [vishalxl/nostr_console#78]
Hi Folks, I'm getting the following error, running the latest release on Windows.

```
Waiting for user posts to come in.....Unhandled exception:
HandshakeException: Handshake error in client (OS Error:
        SSLV3_ALERT_HANDSHAKE_FAILURE(../../third_party/boringssl/src/ssl/tls_record.cc:594)
        HANDSHAKE_FAILURE_ON_CLIENT_HELLO(../../third_party/boringssl/src/ssl/handshake.cc:644))
#0      _SecureFilterImpl._handshake (dart:io-patch/secure_socket_patch.dart:99)
#1      _SecureFilterImpl.handshake (dart:io-patch/secure_socket_patch.dart:142)
#2      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:911)
#3      _RawSecureSocket._tryFilter (dart:io/secure_socket.dart:1040)
<asynchronous suspension>
```

Does anybody know how to fix?

**Comment by jnmclarty** [comment]
@vishalxl I'm happy to help troubleshoot, or supply debugging information, if there is more information I could add.  I'm a dev, but not familiar with Dart or SSL / TLS issues.

**Comment by zapphyre** [comment]
confirmed on Arch.

**Comment by vishalxl** [comment]
Similar error in network handshake reported/seen [here](https://twitter.com/lukeonchain_/status/1619414866628087809)

**Comment by sgon00** [comment]
confirmed on Debian.

**Comment by twofaktor** [comment]
Same issue on Raspbian OS lite arm64

**Comment by rf-peixoto** [comment]
Same on Fedora.

```
Waiting for user posts to come in.....Unhandled exception:
HandshakeException: Handshake error in client (OS Error: 
	SSLV3_ALERT_HANDSHAKE_FAILURE(tls_record.cc:594)
	HANDSHAKE_FAILURE_ON_CLIENT_HELLO(handshake.cc:644))
#0      _SecureFilterImpl._handshake (dart:io-patch/secure_socket_patch.dart:99)
#1      _SecureFilterImpl.handshake (dart:io-patch/secure_socket_patch.dart:142)
#2      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:911)
#3      _RawSecureSocket._tryFilter (dart:io/secure_socket.dart:1040)
```

**Comment by umop3plsdn** [comment]
#77 is the same

**Comment by vishalxl** [comment]
Not seen in windows as of now. Closing.
